/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;
import utils.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.DBConnection;
/**
 *
 * @author admin
 */
public class comp_info_2019 extends javax.swing.JFrame {

    /**
     * Creates new form comp_info_2019
     */
    public comp_info_2019() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Desig = new javax.swing.JLabel();
        internship = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        curr_comp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        platform_link = new javax.swing.JLabel();
        al_name = new javax.swing.JLabel();
        other_links = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        passing_year = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        search_box_comp_2020 = new javax.swing.JTextField();
        submit_comp_2020 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Current Company:");

        Desig.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Desig.setForeground(new java.awt.Color(204, 204, 204));
        Desig.setText("NULL");

        internship.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internship.setForeground(new java.awt.Color(204, 204, 204));
        internship.setText("NULL");

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("NULL");

        curr_comp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        curr_comp.setForeground(new java.awt.Color(204, 204, 204));
        curr_comp.setText("NULL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Designation:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Email id:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Internship:");

        btn6.setBackground(new java.awt.Color(55, 202, 69));
        btn6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn6.setText("Aanamika Misra");
        btn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(55, 202, 69));
        btn7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn7.setText("Nikita Senger");
        btn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(55, 202, 69));
        btn8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn8.setText("Naziya Siddiqui");
        btn8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(55, 202, 69));
        btn9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn9.setText("Gurdeep Kaur");
        btn9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(55, 202, 69));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn2.setText("Shivam Mishra");
        btn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(55, 202, 69));
        btn3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn3.setText("Shakil Ahmad");
        btn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(55, 202, 69));
        btn4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn4.setText("Shubham Giri");
        btn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn10.setBackground(new java.awt.Color(55, 202, 69));
        btn10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn10.setText("Pooja Kashyap");
        btn10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(55, 202, 69));
        btn5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn5.setText("Mahendra Yadav");
        btn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(55, 202, 69));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1.setText("Kulwant Singh");
        btn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Click On The Button...");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Descripton:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Platform Links:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Other Links:");

        platform_link.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        platform_link.setForeground(new java.awt.Color(204, 204, 204));
        platform_link.setText("NULL");

        al_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        al_name.setForeground(new java.awt.Color(204, 204, 204));
        al_name.setText("NULL");

        other_links.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        other_links.setForeground(new java.awt.Color(204, 204, 204));
        other_links.setText("NULL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Year of passing:");

        passing_year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passing_year.setForeground(new java.awt.Color(204, 204, 204));
        passing_year.setText("NULL");

        description.setBackground(new java.awt.Color(0, 51, 102));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setLineWrap(true);
        description.setRows(5);
        description.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        jScrollPane2.setViewportView(description);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search");

        search_box_comp_2020.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_box_comp_2020.setForeground(new java.awt.Color(0, 51, 102));
        search_box_comp_2020.setText("Enter Name");
        search_box_comp_2020.setFocusCycleRoot(true);
        search_box_comp_2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_box_comp_2020ActionPerformed(evt);
            }
        });

        submit_comp_2020.setBackground(new java.awt.Color(255, 153, 0));
        submit_comp_2020.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        submit_comp_2020.setText("Submit");
        submit_comp_2020.setBorder(null);
        submit_comp_2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_comp_2020ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(255, 153, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setText("<--  BACK");
        jButton17.setBorder(null);
        jButton17.setFocusPainted(false);
        jButton17.setFocusable(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(search_box_comp_2020, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit_comp_2020, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Desig, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(internship, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(curr_comp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passing_year, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(al_name, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(platform_link, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(other_links, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(platform_link, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(al_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curr_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(other_links, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(internship, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Desig, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passing_year, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_box_comp_2020, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit_comp_2020, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1282, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Aanamika Misra' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Nikita Senger' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Naziya Siddiqui' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Gurdeep Kaur' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Shivam Mishra' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Shakil Ahmad' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Shubham Giri' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Pooja Kashyap' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Mahendra Yadav' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));

                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        try
        {
            DBConnection connect=new DBConnection();
            java.sql.Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Kulwant Singh' and passedOutYear = 2019");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void search_box_comp_2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_box_comp_2020ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_box_comp_2020ActionPerformed

    private void submit_comp_2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_comp_2020ActionPerformed
        // TODO add your handling code here:
        String name= search_box_comp_2020.getText();

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where passedOutYear = 2019 and full_name like\""+name+"%%\" and dept like 'COMPS'" );

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(this,"Name Doesn't Exist");

        }
    }//GEN-LAST:event_submit_comp_2020ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        new branch_2019().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comp_info_2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comp_info_2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comp_info_2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comp_info_2019.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comp_info_2019().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desig;
    private javax.swing.JLabel al_name;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel curr_comp;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel email;
    private javax.swing.JLabel internship;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel other_links;
    private javax.swing.JLabel passing_year;
    private javax.swing.JLabel platform_link;
    private javax.swing.JTextField search_box_comp_2020;
    private javax.swing.JButton submit_comp_2020;
    // End of variables declaration//GEN-END:variables
}
