/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.DBConnection;


public class it_info extends javax.swing.JFrame {

   
    public it_info() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Desig = new javax.swing.JLabel();
        internship = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        curr_comp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnHarshadMehta3 = new javax.swing.JButton();
        btnHarshadMehta2 = new javax.swing.JButton();
        btnHarshadMehta5 = new javax.swing.JButton();
        btnHarshadMehta6 = new javax.swing.JButton();
        btnHarshadMehta1 = new javax.swing.JButton();
        btnHarshadMehta4 = new javax.swing.JButton();
        btnHarshadMehta7 = new javax.swing.JButton();
        btnHarshadMehta8 = new javax.swing.JButton();
        btnHarshadMehta9 = new javax.swing.JButton();
        btnHarshadMehta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        platform_link = new javax.swing.JLabel();
        al_name = new javax.swing.JLabel();
        other_links = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        passing_year = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        search_box = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1925, 1085));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Current Company:");

        Desig.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Desig.setForeground(new java.awt.Color(204, 204, 204));
        Desig.setText("NULL");

        internship.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internship.setForeground(new java.awt.Color(204, 204, 204));
        internship.setText("NULL");

        email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("NULL");

        curr_comp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        curr_comp.setForeground(new java.awt.Color(204, 204, 204));
        curr_comp.setText("NULL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Designation:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Email id:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Internship:");

        btnHarshadMehta3.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta3.setText("Kanika Kathuria");
        btnHarshadMehta3.setBorder(null);
        btnHarshadMehta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta3ActionPerformed(evt);
            }
        });

        btnHarshadMehta2.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta2.setText("Nitu Kumari");
        btnHarshadMehta2.setBorder(null);
        btnHarshadMehta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta2ActionPerformed(evt);
            }
        });

        btnHarshadMehta5.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta5.setText("Tapasya Das");
        btnHarshadMehta5.setBorder(null);
        btnHarshadMehta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta5ActionPerformed(evt);
            }
        });

        btnHarshadMehta6.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta6.setText("punit khandelwal");
        btnHarshadMehta6.setBorder(null);
        btnHarshadMehta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta6ActionPerformed(evt);
            }
        });

        btnHarshadMehta1.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta1.setText("Sunder Paal");
        btnHarshadMehta1.setBorder(null);
        btnHarshadMehta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta1ActionPerformed(evt);
            }
        });

        btnHarshadMehta4.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta4.setText("Ramdin Verma");
        btnHarshadMehta4.setBorder(null);
        btnHarshadMehta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta4ActionPerformed(evt);
            }
        });

        btnHarshadMehta7.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta7.setText("Sharat Chandran");
        btnHarshadMehta7.setBorder(null);
        btnHarshadMehta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta7ActionPerformed(evt);
            }
        });

        btnHarshadMehta8.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta8.setText("Anjali Juneja");
        btnHarshadMehta8.setBorder(null);
        btnHarshadMehta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta8ActionPerformed(evt);
            }
        });

        btnHarshadMehta9.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta9.setText("Shakshi Sagar");
        btnHarshadMehta9.setBorder(null);
        btnHarshadMehta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehta9ActionPerformed(evt);
            }
        });

        btnHarshadMehta.setBackground(new java.awt.Color(255, 153, 0));
        btnHarshadMehta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarshadMehta.setText("Nahar Singh");
        btnHarshadMehta.setBorder(null);
        btnHarshadMehta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarshadMehtaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Click On The Button...");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Descripton:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Platform Links:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("Other Links:");

        platform_link.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        platform_link.setForeground(new java.awt.Color(204, 204, 204));
        platform_link.setText("NULL");

        al_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        al_name.setForeground(new java.awt.Color(204, 204, 204));
        al_name.setText("NULL");

        other_links.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        other_links.setForeground(new java.awt.Color(204, 204, 204));
        other_links.setText("NULL");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("Year of passing:");

        passing_year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passing_year.setForeground(new java.awt.Color(204, 204, 204));
        passing_year.setText("NULL");

        description.setBackground(new java.awt.Color(0, 51, 102));
        description.setColumns(20);
        description.setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setLineWrap(true);
        description.setRows(5);
        description.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 255)));
        jScrollPane2.setViewportView(description);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search");

        search_box.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search_box.setForeground(new java.awt.Color(0, 51, 102));
        search_box.setText("Enter Name");
        search_box.setFocusCycleRoot(true);
        search_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_boxActionPerformed(evt);
            }
        });

        btnsubmit.setBackground(new java.awt.Color(55, 202, 69));
        btnsubmit.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.setBorder(null);
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(55, 202, 69));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setText("<--  BACK");
        jButton17.setBorder(null);
        jButton17.setFocusPainted(false);
        jButton17.setFocusable(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(847, 847, 847)
                .addComponent(al_name, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(other_links, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(platform_link, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHarshadMehta1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHarshadMehta3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(263, 263, 263)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(internship, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(curr_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 455, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Desig, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passing_year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(al_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(platform_link, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(curr_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarshadMehta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarshadMehta3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(other_links, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHarshadMehta2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHarshadMehta1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(internship, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnHarshadMehta5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Desig, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHarshadMehta7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnHarshadMehta8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHarshadMehta9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passing_year, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_box, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHarshadMehta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta3ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Kanika Kathuria' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta3ActionPerformed

    private void btnHarshadMehta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta2ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Nitu Kumari' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta2ActionPerformed

    private void btnHarshadMehta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta5ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Tapasya Das' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta5ActionPerformed

    private void btnHarshadMehta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta6ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'punit khandelwal' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta6ActionPerformed

    private void btnHarshadMehta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta1ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Sunder Paal' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta1ActionPerformed

    private void btnHarshadMehta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta4ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Ramdin Verma' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta4ActionPerformed

    private void btnHarshadMehta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta7ActionPerformed
        // TODO add your handling code here:
        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Sharat Chandran' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta7ActionPerformed

    private void btnHarshadMehta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta8ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Anjali Juneja' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta8ActionPerformed

    private void btnHarshadMehta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehta9ActionPerformed
        // TODO add your handling code here:

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Shakshi Sagar'and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehta9ActionPerformed

    private void btnHarshadMehtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarshadMehtaActionPerformed
        try
        {
            DBConnection connect = new DBConnection();
            Connection conn = connect.createConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where full_name like 'Nahar Singh' and passedOutYear = 2020");

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_btnHarshadMehtaActionPerformed

    private void search_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_boxActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        String name= search_box.getText();

        try
        {
            DBConnection connect=new DBConnection();
            Connection conn=connect.createConnection();
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from alumni where passedOutYear = 2020 and full_name like\""+name+"%%\" and dept like 'IT'" );

            while(rs.next())
            {
                al_name.setText(rs.getString("full_name"));
                curr_comp.setText(rs.getString("cur_comp"));
                internship.setText(rs.getString("intern_comp"));
                Desig.setText(rs.getString("post"));
                email.setText(rs.getString("email"));
                passing_year.setText(rs.getString("passedOutYear"));
                platform_link.setText(rs.getString("platformLink"));
                other_links.setText(rs.getString("otherLink"));
                description.setText(rs.getString("descr"));
            }

        }
        catch (SQLException e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(this,"Name Doesn't Exist");

        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        new branch().setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(it_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(it_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(it_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(it_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new it_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desig;
    private javax.swing.JLabel al_name;
    private javax.swing.JButton btnHarshadMehta;
    private javax.swing.JButton btnHarshadMehta1;
    private javax.swing.JButton btnHarshadMehta2;
    private javax.swing.JButton btnHarshadMehta3;
    private javax.swing.JButton btnHarshadMehta4;
    private javax.swing.JButton btnHarshadMehta5;
    private javax.swing.JButton btnHarshadMehta6;
    private javax.swing.JButton btnHarshadMehta7;
    private javax.swing.JButton btnHarshadMehta8;
    private javax.swing.JButton btnHarshadMehta9;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel curr_comp;
    private javax.swing.JTextArea description;
    private javax.swing.JLabel email;
    private javax.swing.JLabel internship;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel other_links;
    private javax.swing.JLabel passing_year;
    private javax.swing.JLabel platform_link;
    private javax.swing.JTextField search_box;
    // End of variables declaration//GEN-END:variables
}
